
export const INPUT_NAME_ID = 'INPUT_NAME';
export const INPUT_CARGO_ID = 'INPUT_CARGO ';
export const INPUT_IMAGE_ID = 'INPUT_IMAGE';
export const INPUT_LINKEDIN_ID = 'INPUT_LINKEDIN';
export const INPUT_SELECT_ID = 'SELECT_TIME';
export const BUTTON_CREATE_CARD_ID = 'BUTTON_CREATE_CARD';

export const FACEBOOK_LINK_ID = 'FACEBOOK_LINK'
export const INSTAGRAM_LINK_ID = 'INSTAGRAM_LINK'
export const LINKEDIN_LINK_ID = 'LINKEDIN_LINK'
export const WHATSAPP_LINK_ID = 'WHATSAPP_LINK'